#!/bin/tcsh 

set NFILES    = 900000000
set OUTPUT    = $1
set binName   = $2
set sourceDir = $3
set envScript = $4

source $envScript

setenv h22libs         $sourceDir
setenv ANALTOP         $sourceDir
setenv LD_LIBRARY_PATH $ANALTOP/lib/:$LD_LIBRARY_PATH

cp list.*.dat list.dat 
chmod +x $binName

# Inclusive MC
./$binName -N=$NFILES -TYPE=mcrad -LIST=list.dat -PARS=$ANALTOP/lists/parameters/mc/keppelRadFinal.pars -OUT=$OUTPUT
 
