#!/bin/tcsh 

# User Parameters 
set numberOfJobs = 20
set binDir       = "/u/home/dmriser/clas/retro-sidis/mysidis"
set binName      = "mysidis"
set sourceDir    = "/u/home/dmriser/clas/analysis-projects/farm/analysis" 
set outDir       = "/volatile/clas12/dmriser/farm_out/"
set outName      = "sidis_xs_debug_00"
set runScript    = "goAnalyze"
set fileList     = "/u/home/dmriser/clas/analysis-main/lists/files/data/good_files.dat"
set sourceCode   = "/u/home/dmriser/clas/analysis-main/"
set envScript    = "/u/home/dmriser/environment/jlab-root6.env"

# Create the output
# dir if it doesnt exist
mkdir -p $outDir/$outName
cp $runScript $outDir/$outName/$runScript

# Splits the master list into numberOfJobs
# smaller lists to be used on the nodes.
./buildFileList $numberOfJobs $fileList

# Get our list of jobs 
set allLists = `ls *.dat`

# Send the jobs
set currentList = 1
foreach list ($allLists) 
    ./buildJsub $allLists[$currentList] analysis.$currentList.jsub $binDir $binName $outDir/$outName $outName.$currentList.root $sourceDir $runScript $sourceCode $envScript
    mv $list $outDir/$outName/$list
    jsub analysis.$currentList.jsub 
    @ currentList++
end

# Clean 
rm analysis.*.jsub 
rm list.*.dat

# Brag about it 
echo " >> Done, output dir created. "
ls $outDir/$outName
